### ISSUE TITLE
hackRF compatibility

### ISSUE THREAD

**Issue by gfrancqu** [Cognosec/SecBee#3]
Hi,

does secBee have to work with USRP ? Is it possible to make it work with hackRF ? 
If so.. what kind of modification would be needed ?

best regards,
Guillaume

**Comment by zu1na** [comment]
Hi,

currently sending/injecting packets is only possible with the USRP. Sniffing and extracting data also works with the hackrf.

Problem is the GNU Radio Osmocom Sink. The packets will be queued and only transmitted if a certain amount of data is reached. Maybe this will be fixed in future versions.

Best,
Tobias
